export const documentLocalState = {
  __typename: 'documentCreation',
  documentId: 'A-23',
  date: '2019-11-12',
  dueDate: '2020-11-01',
  observations: 'test',
  annotation: 'test annotation',
  termsConditions: '30%',
  documentType: 'order',
  client: null,
  retentions: [
    {
      __typename: 3,
      id: 'sss',
      name: 'Sobre la renta',
      percentage: 20.0,
      description: 'testing retention',
      type: 'Fuente',
    },
  ],
  currency: {
    id: '002',
    code: 'USD',
    symbol: '$',
    exchangeRate: 54.5,
  },
  seller: {
    code: '0023',
    name: 'Keysy',
    status: true,
    identification: '002323',
    observations: 'testing',
  },
  priceList: {
    id: '001',
    name: 'Distribuidor',
    status: true,
    type: 'percentage',
    percentage: 20.0,
  },
  total: 0.0,
  totalPaid: 0.0,
  totalTax: 0.0,
  balance: 0.0,
  NCF: '3903949493',
  orderNumber: '12312',
  items: [],
};

export default documentLocalState;
